apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
  - name: "81"
    port: 81
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
