apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        taskmanager: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: taskmanager
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: registry.ng.bluemix.net/yheng/mysql:8.0.2
        name: db
        ports:
        - containerPort: 3306
        resources: {}
#        volumeMounts:
#        - mountPath: /docker-entrypoint-initdb.d
#          name: db-claim0
      restartPolicy: Always
#      volumes:
#      - name: db-claim0
#        persistentVolumeClaim:
#          claimName: db-claim0

---


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    taskmanager: db
  name: db
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    nodePort: 31000
  selector:
    taskmanager: db
status:
  loadBalancer: {}
 

---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        taskmanager: api
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: 184.172.247.22
        - name: DB_PORT
          value: "31000"
        image: registry.ng.bluemix.net/yheng/taskmanager-service
        name: api
        ports:
        - containerPort: 80
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}

---


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    taskmanager: api
  name: api
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 30000
  selector:
    taskmanager: api
status:
  loadBalancer: {}
  

